import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { Header } from "~/components/Header";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>T3 Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content />
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: sessionData } = useSession();
  const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
    undefined,
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div>{JSON.stringify(topics)}</div>
  )
};
